cathedral/urls.py
from django.urls import path
from django_hosts.resolvers import reverse
from cathedral import views

app_name = 'cathedral'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    #path('test/', views.TestPageView.as_view(), name='test'),

    path('reflections/', views.ReflectionListView.as_view(), name='reflection_list'),
    path('reflections/<int:year>/<int:month>/<int:day>/<slug:reflection>/', views.reflection_detail, name='reflection_detail'),

    path('parishes/', views.ParishPageView.as_view(), name='parish'),
    path('gallery/', views.GalleryPageView.as_view(), name='gallery'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    path('basecontact/', views.basecontactView, name='basecontact'),
]

stkevins/urls.py
from django.urls import path, include
from stkevins import views

app_name = 'stkevins'

urlpatterns = [
    path('', views.KevinsPageView.as_view(), name='stkevins'),

    path('calender/', views.EventListView.as_view(), name='event_list'),
    path('calender/<int:year>/<int:month>/<int:day>/<slug:event>/', views.event_detail, name='event_detail'),

    #path('sacraments/', views.SacramentListView.as_view(), name='sacrament_list'),
    #path('sacraments/<slug:slug>/', views.SacramentDetailView.as_view(), name='sacrament_detail'),

    #path('communities/', views.CommunityListView.as_view(), name='community_list'),
    #path('communities/<slug:slug>/', views.CommunityDetailView.as_view(), name='community_detail'),

    #path('societies/', views.SocietyListView.as_view(), name='society_list'),
    #path('societies/<slug:slug>/', views.SocietyDetailView.as_view(), name='society_detail'),

    #path('parishioners/', views.ParishionerListView.as_view(), name='parishioner_list'),
    #path('parishioner/<slug:slug>/', views.ParishionerDetailView.as_view(), name='parishioner_detail'),

    #path('levy/', views.LevyListView.as_view(), name='levy_list'),
    #path('levy/<int:year>/<int:month>/<int:day>/<slug:levy>/', views.levy_detail, name='levy_detail'),

    #path('contribution/', views.ContributionListView.as_view(), name='contribution_list'),
    #path('contribution/<int:year>/<int:month>/<int:day>/<slug:contribution>/', views.contribution_detail, name='contrinution_detail'),

    path('history/', views.HistoryPageView.as_view(), name='history'),
    path('contact/', views.ContactPageView.as_view(), name='contact'),
    path('gallery/', views.GalleryPageView.as_view(), name='gallery'),

    #path('search/', views.SearchResultsView.as_view(), name='search_results'),

    path('group_membership/', views.groupmembershipView, name='groupmembership'),
    path('society_membership/', views.societymembershipView, name='societymembership'),

]

stkevins/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, ListView, DetailView
from django.db.models import Q

from .models import Event, AdSlide, ParishPriest, HomeBanner

from .forms import GroupForm, SocietyForm

# Create your views here.
class KevinsPageView(TemplateView):
    template_name = 'stkevins/stkevins_home.html'

    def get_context_data(self, **kwargs):
        context = super(KevinsPageView, self).get_context_data(**kwargs)
        context["home_banner"] = HomeBanner.objects.get(id=1)
        context["parish_priest"] = ParishPriest.objects.get(id=1)
        context["slider"] = AdSlide.objects.all()
        return context

class EventListView(ListView):
    queryset = Event.published.all()
    context_object_name = 'event_list'
    paginate_by = 4
    template_name = 'stkevins/event_list.html'

def event_detail(request, year, month, day, event):
    event = get_object_or_404(Event, slug=event,
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    return render(request, 'stkevins/event_detail.html', {'event': event,})


"""
class SacramentListView(ListView):
    model = Sacrament
    context_object_name = 'sacrament_list'
    template_name = 'stkevins/sacrament_list.html'

class SacramentDetailView(DetailView):
    model = Sacrament
    context_object_name = 'sacrament'
    template_name = 'stkevins/sacrament_detail.html'

    def get_object(self, queryset=None):
        return Sacrament.objects.get(slug=self.kwargs.get("slug"))

class SocietyListView(ListView):
    model = Society
    context_object_name = 'society_list'
    template_name = 'stkevins/society_list.html'

class SocietyDetailView(DetailView):
    model = Society
    context_object_name = 'society'
    template_name = 'stkevins/society_detail.html'

    def get_object(self, queryset=None):
        return Society.objects.get(slug=self.kwargs.get("slug"))

class CommunityListView(ListView):
    model = Community
    context_object_name = 'community_list'
    template_name = 'stkevins/community_list.html'

class CommunityDetailView(DetailView):
    model = Community
    context_object_name = 'community'
    template_name = 'stkevins/community_detail.html'

    def get_object(self, queryset=None):
        return Community.objects.get(slug=self.kwargs.get("slug"))

class LevyListView(ListView):
    model = Levy
    context_object_name = 'levy_list'
    template_name = 'stkevins/levy_list.html'

def levy_detail(request, year, month, day, levy):
    levy = get_object_or_404(Levy, slug=levy,
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    return render(request, 'stkevins/levy_detail.html', {'levy': levy,})

class ContributionListView(ListView):
    model = Contribution
    context_object_name = 'contribution_list'
    template_name = 'stkevins/contribution_list.html'

def contribution_detail(request, year, month, day, contribution):
    contribution = get_object_or_404(Contribution, slug=contribution,
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    return render(request, 'stkevins/contribution_detail.html', {'contribution': contribution,})

class ParishionerListView(ListView):
    model = Parishioner
    context_object_name = 'parishioner_list'
    template_name = 'stkevins/parishioner_list.html'

class ParishionerDetailView(DetailView):
    model = Parishioner
    context_object_name = 'parishioner'
    template_name = 'stkevins/parishioner_detail.html'

    def get_object(self, queryset=None):
        return Parishioner.objects.get(slug=self.kwargs.get("slug"))
"""

class ContactPageView(TemplateView):
    template_name = 'stkevins/contact.html'

class HistoryPageView(TemplateView):
    template_name = 'stkevins/history.html'

class GalleryPageView(TemplateView):
    template_name = 'stkevins/gallery.html'
"""
class SearchResultsView(ListView):
    model = Parishioner
    template_name = 'stkevins/search_results.html'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Parishioner.objects.filter(
            Q(name__icontains=query) | Q(id_number__icontains=query)
        )
        return object_list
"""

def groupmembershipView(request):
    if request.method == 'GET':
        form = GroupForm()
    else:
        form = GroupForm(request.POST)
        if form.is_valid():
            subject = "Group Membership Inquiry"
            body = {
                'name': form.cleaned_data['name'],
                'parishioner_id': form.cleaned_data['parishioner_id'],
                'group': form.cleaned_data['group'],
                'email': form.cleaned_data['email'],
                'phone': form.cleaned_data['phone'],
                'motivation': form.cleaned_data['motivation'],
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'info@parishbits.com', ['juddyblaise@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.success(request, 'Message Successfully Sent!', extra_tags='alert-box--success')
            return redirect('stkevins:groupmembership')
        messages.warning(request, 'Error. Message was not sent!', extra_tags='alert-box--error')
    return render(request, "stkevins/group_membership.html", {'form': form})

def societymembershipView(request):
    if request.method == 'GET':
        form = SocietyForm()
    else:
        form = SocietyForm(request.POST)
        if form.is_valid():
            subject = "Society Membership Inquiry"
            body = {
                'name': form.cleaned_data['name'],
                'parishioner_id': form.cleaned_data['parishioner_id'],
                'society': form.cleaned_data['society'],
                'email': form.cleaned_data['email'],
                'phone': form.cleaned_data['phone'],
                'motivation': form.cleaned_data['motivation'],
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'info@parishbits.com', ['juddyblaise@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.success(request, 'Message Successfully Sent!', extra_tags='alert-box--success')
            return redirect('stkevins:societymembership')
        messages.warning(request, 'Error. Message was not sent!', extra_tags='alert-box--error')
    return render(request, "stkevins/society_membership.html", {'form': form})

templates/_base.html
{% load static %}

{% load crispy_forms_tags %}

{% load hosts %}

<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}Parishbits{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Hidayah - v4.6.0
  * Template URL: https://bootstrapmade.com/hidayah-free-simple-html-template-for-corporate/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-inner-pages">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="{% url 'cathedral:home' %}">Parishbits</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto" href="{% url 'cathedral:home' %}">Home</a></li>
          <li><a class="nav-link  scrollto" href="{% url 'cathedral:parish' %}">Parishes</a></li>
          <li><a class="nav-link scrollto" href="{% url 'cathedral:gallery' %}">Gallery</a></li>
          <li><a class="nav-link scrollto" href="{% url 'cathedral:contact' %}">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  {% block content %}
  {% endblock content %}

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact section-bg">
      <div class="container-fluid">

        <div class="section-title">
          <h2>Contact</h2>
          <h3>Get In Touch With <span>Us</span></h3>
          <p>For enquiries about any of the parishes listed and how to enroll your parish on ParishBits, Kindly contact us.</p>
        </div>

        <div class="row justify-content-center">
          <div class="col-xl-10">
            <div class="row">

              <div class="col-lg-6">

                <div class="row justify-content-center">

                  <div class="col-md-6 info d-flex flex-column align-items-stretch">
                    <i class="bx bx-map"></i>
                    <h4>Address</h4>
                    <p>Block E4, Finance Quarters,<br>Wuye, Abuja</p>
                  </div>
                  <div class="col-md-6 info d-flex flex-column align-items-stretch">
                    <i class="bx bx-phone"></i>
                    <h4>Call Us</h4>
                    <p>+234 706 555 6423<br>+234 903 508 8091</p>
                  </div>
                  <div class="col-md-6 info d-flex flex-column align-items-stretch">
                    <i class="bx bx-envelope"></i>
                    <h4>Email Us</h4>
                    <p>juddyblaise@gmail.com<br>okeyluvsu2004@gmail.com</p>
                  </div>
                  <div class="col-md-6 info d-flex flex-column align-items-stretch">
                    <i class="bx bx-time-five"></i>
                    <h4>Working Hours</h4>
                    <p>Mon - Fri: 9AM to 5PM<br></p>
                  </div>

                </div>

              </div>

              <div class="col-lg-6">
                <form method="post" action="{% url 'cathedral:basecontact' %}" role="form" class="php-email-form">
                  
                  {% csrf_token %}

                  <div class="row">
                    <div class="col-md-6 form-group">
                      <label for="name">Your Name</label>
                      {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col-md-6 form-group mt-3 mt-md-0">
                      <label for="email">Your Email</label>
                      {{ form.email|as_crispy_field }}
                    </div>
                  </div>

                  <div class="form-group mt-3">
                    <label for="subject">Subject</label>
                    {{ form.subject|as_crispy_field }}
                  </div>

                  <div class="form-group mt-3">
                    <label for="message">Message</label>
                    {{ form.message|as_crispy_field }}
                  </div>

                  <div class="my-3">
                    {% include 'messages.html' %}
                  </div>

                  <div class="text-center"><button type="submit">Send Message</button></div>


                </form>
              </div>

            </div>
          </div>
        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    

    <div class="footer-top">
      <div class="container-fluid">
        <div class="row justify-content-center">
          <div class="col-xl-10">
            <div class="row">

              <div class="col-lg-3 col-md-6 footer-links">
                <h4>Useful Links</h4>
                <ul>
                  <li><i class="bx bx-chevron-right"></i> <a href="{% url 'cathedral:home' %}">Home</a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="{% url 'cathedral:parish' %}">Parishes</a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="{% url 'cathedral:gallery' %}">Gallery</a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="{% url 'cathedral:contact' %}">Contact</a></li>
                </ul>
              </div>

              

              <div class="col-lg-3 col-md-6 footer-contact">
                <h4>Contact Us</h4>
                <p>
                  Block E4, Finance Quarters, <br>
                  Wuye, Abuja.<br>
                  Nigeria <br><br>
                  <strong>Phone:</strong> +234 706 555 6423<br>
                  <strong>Email:</strong> juddyblaise@gmail.com<br>
                </p>

              </div>

              <div class="col-lg-3 col-md-6 footer-info">
                <h3><a href="{% url 'cathedral:home' %}">ParishBits</a></h3>
                <p>A Collection of parishes aroud you.</p>
                <div class="social-links mt-3">
                  <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                  <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                  <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                  <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                  <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Hidayah</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/hidayah-free-simple-html-template-for-corporate/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/gbase.html
{% load static %}

{% load crispy_forms_tags %}

{% load hosts %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>{% block title %}St Kevins, Jikwoyi{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'assets/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <!-- script
    ================================================== -->
    <script src="{% static 'assets/js/modernizr.js' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'assets/img/site.webmanifest' %}">

</head>

<body id="top">

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-jump">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header">

        <div class="header-logo">
            <a class="site-logo" href="#">
                <img src="{% static 'assets/img/logo.svg' %}" alt="Homepage">
            </a>
        </div>

        <nav class="header-nav-wrap">
            <ul class="header-nav">
                <li class="current"><a href="{% url 'stkevins:stkevins' %}" title="Home">Home</a></li>
                <li><a href="{% url 'stkevins:event_list' %}" title="calender">Calendar</a></li>
                <li><a href="{% url 'stkevins:parishioner_list' %}" title="parishioners">Parishioners</a></li>
                <li><a href="{% url 'stkevins:gallery' %}" title="gallery">Gallery</a></li>
                <li><a href="{% url 'stkevins:history' %}" title="history">History</a></li>
                <li><a href="{% url 'stkevins:contact' %}" title="Contact us">Contact</a></li>	
            </ul>
        </nav>

        <a class="header-menu-toggle" href="#0"><span>Menu</span></a>

    </header> <!-- end s-header -->


    {% block content %}
    {% endblock content %}


    <!-- footer
    ================================================== -->
    <footer class="s-footer">

        <div class="row footer-top">
            <div class="column large-4 medium-5 tab-full">
                <div class="footer-logo">
                    <a class="site-footer-logo" href="#">
                        <img src="{% static 'assets/img/logo.svg' %}" alt="Homepage">
                    </a>
                </div>  <!-- footer-logo -->
                <p>
                Laborum ad explicabo. Molestiae voluptates est. Quisquam labore tenetur 
                et assumenda voluptatibus a beatae. Rerum odio ducimus reprehenderit 
                sit animi laborum nostrum dolorum animi voluptates est voluptatibus a beatae. 
                </p>
            </div>
            <div class="column large-half tab-full">
                <div class="row">
                    <div class="column large-7 medium-full">
                        <h4 class="h6">Our Location</h4>
                        <p>
                        1600 Amphitheatre Parkway <br>
                        Mountain View, California <br>
                        94043 US
                        </p>
        
                        <p>
                        <a href="https://goo.gl/maps/bc7C7eYtSmnNs6216" target="_blank" class="btn btn--footer">Get Direction</a>
                        </p>
                    </div>
                    <div class="column large-5 medium-full">
                        <h4 class="h6">Quick Links</h4>
                        <ul class="footer-list">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About</a></li>
                            <li><a href="#">Volunteer</a></li>
                            <li><a href="#">Connect Groups</a></li>
                            <li><a href="#">Upcoming Events</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!-- end footer-top -->

        <div class="row footer-bottom">
            <div class="column ss-copyright">
                <span>© Copyright Hesed 2019</span> 
                <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
            </div>
        </div> <!-- footer-bottom -->

        <div class="ss-go-top">
            <a class="smoothscroll" title="Back to Top" href="#top">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0l8 9h-6v15h-4v-15h-6z"/></svg>
            </a>
        </div> <!-- ss-go-top -->

    </footer> <!-- end s-footer -->


    <!-- Java Script
    ================================================== -->
    <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'assets/js/plugins.js' %}"></script>
    <script src="{% static 'assets/js/stkev_main.js' %}"></script>

</body>

templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    {{ message }}
  </div>
{% endfor %}

templates/messagess.html
{% for message in messages %}
    <div class="alert-box {{ message.tags }} hideit" role="alert">
        <p>{{ message }}</p>
        <i class="fa fa-times alert-box__close" aria-hidden="true"></i>
    </div><!-- end error -->
{% endfor %}